spring:
  application:
    name: LibraryManagementSystem

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/LMS
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: boot
      password: spring
